---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
	command: /opt/apache-tomcat-8.5.83/bin/startup.sh
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: target/webappExample.war
        dest: /opt/apache-tomcat-8.5.83/webapps
...
