  ---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        command: //opt/apache-tomcat-8.5.83/bin/startup.sh
		      sudo: true
		      sudo_user: ec2-user
          state: started
          enabled: True
    - name: Deploy static website
      copy:
        src: target/webappExample.war
        dest: /opt/apache-tomcat-8.5.83/webapps
...
